/// <reference lib="webworker" />

/**
 * self.mp3 service worker.
 *
 * Three jobs, each with a deliberately different strategy:
 *
 *  1. **App shell** — cache-first with a background update. The app opens
 *     instantly and offline; a new build is picked up on the next visit.
 *  2. **Audio** — cache-first, and critically it answers range requests out of
 *     the cache. Without that, iOS Safari will not play a cached file at all,
 *     because it always asks for `Range: bytes=0-1` first.
 *  3. **API** — network-first with a cached fallback for the library, so a
 *     sleeping Mac degrades to "yesterday's library" rather than an error.
 *
 * Built for the web (GitHub Pages, docs/SYNC.md) there is no Mac: a song or a
 * cover this device does not have yet is fetched from the bucket through the
 * doorman instead, with the session the app keeps in IndexedDB. For the
 * player, the whole song is fetched and kept before any of it plays.
 *
 * The app may live under a path (`/selfmp3/` on Pages), so every path here is
 * taken relative to the scope this worker was registered with.
 *
 * Written by hand rather than generated by Workbox: the range-request handling
 * is the whole point of this file and is not something a generic recipe does.
 */

declare const self: ServiceWorkerGlobalScope

const VERSION = 'v1'
const SHELL_CACHE = `selfmp3-shell-${VERSION}`
const API_CACHE = `selfmp3-api-${VERSION}`
const AUDIO_CACHE = 'selfmp3-audio-v1'

/** Caches this worker owns. Anything else from an old build gets deleted. */
const OWNED_CACHES = new Set([SHELL_CACHE, API_CACHE, AUDIO_CACHE])

/** `/` served by the Mac, `/selfmp3/` on GitHub Pages: this worker's scope. */
const BASE = new URL(self.registration.scope).pathname

/** The web build registers `sw.js?cloud=1` (main.tsx): only then is there a bucket to ask. */
const CLOUD = new URL(self.location.href).searchParams.get('cloud') === '1'
const INDEX = `${BASE}index.html`

const SHELL_URLS = [BASE, INDEX, `${BASE}manifest.webmanifest`, `${BASE}icons/icon.svg`]

self.addEventListener('install', event => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(SHELL_CACHE)
      // Individually, so one 404 does not fail the whole install.
      await Promise.allSettled(SHELL_URLS.map(url => cache.add(url)))
      // Take over immediately; waiting for every tab to close is not the
      // behaviour anyone wants from their own music app.
      await self.skipWaiting()
    })(),
  )
})

self.addEventListener('activate', event => {
  event.waitUntil(
    (async () => {
      const names = await caches.keys()
      await Promise.all(
        names
          .filter(name => name.startsWith('selfmp3-') && !OWNED_CACHES.has(name))
          .map(name => caches.delete(name)),
      )
      await self.clients.claim()
    })(),
  )
})

self.addEventListener('message', event => {
  const data: unknown = event.data
  if (typeof data === 'object' && data !== null && 'type' in data) {
    if ((data as { type: string }).type === 'SKIP_WAITING') void self.skipWaiting()
  }
})

self.addEventListener('fetch', event => {
  const request = event.request
  if (request.method !== 'GET' && request.method !== 'HEAD') return

  const url = new URL(request.url)
  // Never touch cross-origin requests (album art from a thumbnail host, etc).
  if (url.origin !== self.location.origin) return

  /*
   * The event stream is never intercepted.
   *
   * It is an infinite response: the network-first handler below would await
   * `fetch()` and then hold a response that never completes, and any attempt
   * to cache it would buffer forever. Falling through to the browser lets
   * EventSource own the connection, including its own reconnect.
   */
  if (url.pathname === `${BASE}api/events`) return

  // Listening before importing: a range stream proxied from YouTube, never
  // worth caching, and the browser owns its connection best (a seek drops it).
  if (url.pathname === `${BASE}api/import/listen`) return

  if (url.pathname.startsWith(`${BASE}api/stream/`)) {
    event.respondWith(handleAudio(request, url))
    return
  }

  if (url.pathname.startsWith(`${BASE}api/art/`)) {
    event.respondWith(cacheFirst(request, API_CACHE, { replaceOtherVersions: true }))
    return
  }

  if (url.pathname.startsWith(`${BASE}api/`)) {
    event.respondWith(networkFirst(request))
    return
  }

  event.respondWith(handleShell(request, url))
})

/**
 * Serve audio, honouring range requests from the cache.
 *
 * This is the function that makes offline playback actually work. The cache
 * holds a complete 200 response; a player asking for bytes 500-999 gets a
 * correctly-formed 206 slice built here, because the Cache API will not do it.
 */
async function handleAudio(request: Request, url: URL): Promise<Response> {
  const cache = await caches.open(AUDIO_CACHE)
  const cacheKey = url.pathname
  const cached = await cache.match(cacheKey)

  if (cached) {
    const range = request.headers.get('range')
    if (!range) return cached
    return sliceResponse(cached, range)
  }

  const fromBucket = await bucketFileFor(url, 'audio')
  if (fromBucket) {
    const range = request.headers.get('range')
    // A download asks for the whole file with no range: pass it straight
    // through, and the page keeps it as it arrives, counting the bytes.
    if (!range) return fetchFromBucket(fromBucket)
    // The player asks for a range. Nothing plays until it is on the device, so
    // the whole song is fetched and kept first, and the range cut from that.
    const response = await fetchFromBucket(fromBucket)
    if (!response.ok) return response
    const complete = new Response(await response.arrayBuffer(), {
      status: 200,
      headers: response.headers,
    })
    await cache.put(cacheKey, complete.clone())
    return sliceResponse(complete, range)
  }

  // Not cached — go to the network and do not store it. Songs enter the cache
  // only through an explicit sync, so casual listening cannot quietly fill up
  // the phone's storage.
  try {
    return await fetch(request)
  } catch {
    return new Response('This song is not available offline.', {
      status: 503,
      statusText: 'Offline',
      headers: { 'Content-Type': 'text/plain' },
    })
  }
}

/** Build a 206 Partial Content response from a complete cached one. */
async function sliceResponse(response: Response, rangeHeader: string): Promise<Response> {
  const buffer = await response.arrayBuffer()
  const size = buffer.byteLength

  const match = /^bytes=(\d*)-(\d*)$/.exec(rangeHeader.trim())
  if (!match) return new Response(buffer, { status: 200, headers: response.headers })

  const [, rawStart = '', rawEnd = ''] = match

  let start: number
  let end: number

  if (rawStart === '') {
    // Suffix range: the last N bytes.
    const suffix = Number(rawEnd)
    if (!Number.isFinite(suffix) || suffix <= 0) return rangeNotSatisfiable(size)
    start = Math.max(0, size - suffix)
    end = size - 1
  } else {
    start = Number(rawStart)
    end = rawEnd === '' ? size - 1 : Math.min(Number(rawEnd), size - 1)
  }

  if (!Number.isFinite(start) || !Number.isFinite(end) || start > end || start >= size) {
    return rangeNotSatisfiable(size)
  }

  const headers = new Headers()
  headers.set('Content-Type', response.headers.get('content-type') ?? 'audio/mp4')
  headers.set('Content-Length', String(end - start + 1))
  headers.set('Content-Range', `bytes ${start}-${end}/${size}`)
  headers.set('Accept-Ranges', 'bytes')
  headers.set('Cache-Control', 'private, max-age=31536000, immutable')

  return new Response(buffer.slice(start, end + 1), {
    status: 206,
    statusText: 'Partial Content',
    headers,
  })
}

function rangeNotSatisfiable(size: number): Response {
  return new Response(null, {
    status: 416,
    statusText: 'Range Not Satisfiable',
    headers: { 'Content-Range': `bytes */${size}` },
  })
}

/**
 * API requests: network first, falling back to the last good response.
 *
 * Only safe, idempotent reads are cached, and only the library snapshot is
 * worth serving stale — the import queue or live stats would be actively
 * misleading if they were hours old.
 */
async function networkFirst(request: Request): Promise<Response> {
  const cacheable = new URL(request.url).pathname === `${BASE}api/library`

  try {
    const response = await fetch(request)
    if (cacheable && response.ok) {
      const cache = await caches.open(API_CACHE)
      await cache.put(request, response.clone())
    }
    return response
  } catch {
    if (cacheable) {
      const cached = await caches.match(request)
      if (cached) return cached
    }
    return new Response(JSON.stringify({ error: 'offline', code: 'offline' }), {
      status: 503,
      headers: { 'Content-Type': 'application/json' },
    })
  }
}

/**
 * Cache-first, keyed on the full URL including `?v=`.
 *
 * With `replaceOtherVersions`, storing a response first drops every other
 * version of the same path, so a cover that changes does not leave the old
 * one behind forever.
 */
async function cacheFirst(
  request: Request,
  cacheName: string,
  options: { replaceOtherVersions?: boolean } = {},
): Promise<Response> {
  const cached = await caches.match(request)
  if (cached) return cached
  try {
    const fromBucket = await bucketFileFor(new URL(request.url), 'cover')
    const response = fromBucket ? await fetchFromBucket(fromBucket) : await fetch(request)
    if (response.ok) {
      const cache = await caches.open(cacheName)
      if (options.replaceOtherVersions) {
        await cache.delete(new URL(request.url).pathname, { ignoreSearch: true })
      }
      await cache.put(request, response.clone())
    }
    return response
  } catch {
    return new Response(null, { status: 503 })
  }
}

/**
 * The app shell.
 *
 * Navigations always resolve to `index.html` so client-side routes work
 * offline — opening the app on `/stats` with no network must not 404.
 */
async function handleShell(request: Request, url: URL): Promise<Response> {
  const cache = await caches.open(SHELL_CACHE)

  if (request.mode === 'navigate') {
    try {
      const response = await fetch(request)
      if (response.ok) await cache.put(INDEX, response.clone())
      return response
    } catch {
      const cached = (await cache.match(INDEX)) ?? (await cache.match(BASE))
      return cached ?? new Response('Offline', { status: 503 })
    }
  }

  const cached = await cache.match(request)
  if (cached) {
    // Refresh in the background so the next load has the new build, without
    // making this one wait for the network.
    void (async () => {
      try {
        const fresh = await fetch(request)
        if (fresh.ok) await cache.put(request, fresh)
      } catch {
        // Offline: the cached copy stays.
      }
    })()
    return cached
  }

  try {
    const response = await fetch(request)
    // Only cache our own build output, not arbitrary paths.
    const ownOutput =
      url.pathname.startsWith(`${BASE}assets/`) || url.pathname.startsWith(`${BASE}icons/`)
    if (response.ok && ownOutput) {
      await cache.put(request, response.clone())
    }
    return response
  } catch {
    return new Response(null, { status: 503 })
  }
}

// --- The bucket, for the web build --------------------------------------------

/**
 * Where the app keeps the doorman session and each song's files: IndexedDB,
 * database `selfmp3`, store `kv` — see offline/mirror.ts, lib/cloud/session.ts
 * (`cloud-session`) and lib/cloud/library.ts (`cloud-files`).
 */
const DB_NAME = 'selfmp3'
const DB_STORE = 'kv'
/** offline/mirror.ts's DB_VERSION. Opened with the same version and upgrade, whoever gets there first. */
const DB_VERSION = 1

interface BucketFile {
  readonly url: string
  readonly token: string
}

/**
 * The bucket file behind a stream or cover URL, when the app is signed in to
 * the doorman — which only the web build is. Null otherwise: served by the
 * Mac, nothing here changes.
 */
async function bucketFileFor(url: URL, kind: 'audio' | 'cover'): Promise<BucketFile | null> {
  if (!CLOUD) return null
  const match = /\/api\/(?:stream|art)\/(\d+)$/.exec(url.pathname)
  if (!match?.[1]) return null
  try {
    const session = (await readStored('cloud-session')) as {
      doormanUrl?: unknown
      token?: unknown
    } | null
    if (typeof session?.doormanUrl !== 'string' || typeof session.token !== 'string') return null
    const files = (await readStored('cloud-files')) as Record<
      string,
      { audio?: unknown; cover?: unknown }
    > | null
    const key = files?.[match[1]]?.[kind]
    if (typeof key !== 'string') return null
    return { url: `${session.doormanUrl}/v1/files/${key}`, token: session.token }
  } catch {
    return null
  }
}

/** A file from the bucket, as a plain same-origin response. */
async function fetchFromBucket(file: BucketFile): Promise<Response> {
  try {
    const response = await fetch(file.url, { headers: { Authorization: `Bearer ${file.token}` } })
    const headers = new Headers()
    for (const name of ['content-type', 'content-length', 'etag']) {
      const value = response.headers.get(name)
      if (value) headers.set(name, value)
    }
    headers.set('Cache-Control', 'private, max-age=31536000, immutable')
    return new Response(response.body, { status: response.status, headers })
  } catch {
    return new Response('This song is not on this device, and the cloud cannot be reached.', {
      status: 503,
      statusText: 'Offline',
      headers: { 'Content-Type': 'text/plain' },
    })
  }
}

function readStored(key: string): Promise<unknown> {
  return new Promise((resolve, reject) => {
    const open = indexedDB.open(DB_NAME, DB_VERSION)
    open.onupgradeneeded = () => {
      if (!open.result.objectStoreNames.contains(DB_STORE)) open.result.createObjectStore(DB_STORE)
    }
    open.onerror = () => reject(open.error ?? new Error('could not open IndexedDB'))
    open.onsuccess = () => {
      const db = open.result
      if (!db.objectStoreNames.contains(DB_STORE)) {
        db.close()
        resolve(null)
        return
      }
      const request = db.transaction(DB_STORE, 'readonly').objectStore(DB_STORE).get(key)
      request.onsuccess = () => {
        db.close()
        resolve(request.result ?? null)
      }
      request.onerror = () => {
        db.close()
        reject(request.error ?? new Error('IndexedDB read failed'))
      }
    }
  })
}

export {}
