/// <reference lib="webworker" />

/**
 * self.mp3 service worker.
 *
 * Three jobs, each with a deliberately different strategy:
 *
 *  1. **App shell** — cache-first with a background update. The app opens
 *     instantly and offline; a new build is picked up on the next visit.
 *  2. **Audio** — cache-first, and critically it answers range requests out of
 *     the cache. Without that, iOS Safari will not play a cached file at all,
 *     because it always asks for `Range: bytes=0-1` first.
 *  3. **API** — network-first with a cached fallback for the library, so a
 *     sleeping Mac degrades to "yesterday's library" rather than an error.
 *
 * Written by hand rather than generated by Workbox: the range-request handling
 * is the whole point of this file and is not something a generic recipe does.
 */

declare const self: ServiceWorkerGlobalScope

const VERSION = 'v1'
const SHELL_CACHE = `selfmp3-shell-${VERSION}`
const API_CACHE = `selfmp3-api-${VERSION}`
const AUDIO_CACHE = 'selfmp3-audio-v1'

/** Caches this worker owns. Anything else from an old build gets deleted. */
const OWNED_CACHES = new Set([SHELL_CACHE, API_CACHE, AUDIO_CACHE])

const SHELL_URLS = ['/', '/index.html', '/manifest.webmanifest', '/icons/icon.svg']

self.addEventListener('install', event => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(SHELL_CACHE)
      // Individually, so one 404 does not fail the whole install.
      await Promise.allSettled(SHELL_URLS.map(url => cache.add(url)))
      // Take over immediately; waiting for every tab to close is not the
      // behaviour anyone wants from their own music app.
      await self.skipWaiting()
    })(),
  )
})

self.addEventListener('activate', event => {
  event.waitUntil(
    (async () => {
      const names = await caches.keys()
      await Promise.all(
        names
          .filter(name => name.startsWith('selfmp3-') && !OWNED_CACHES.has(name))
          .map(name => caches.delete(name)),
      )
      await self.clients.claim()
    })(),
  )
})

self.addEventListener('message', event => {
  const data: unknown = event.data
  if (typeof data === 'object' && data !== null && 'type' in data) {
    if ((data as { type: string }).type === 'SKIP_WAITING') void self.skipWaiting()
  }
})

self.addEventListener('fetch', event => {
  const request = event.request
  if (request.method !== 'GET' && request.method !== 'HEAD') return

  const url = new URL(request.url)
  // Never touch cross-origin requests (album art from a thumbnail host, etc).
  if (url.origin !== self.location.origin) return

  /*
   * The event stream is never intercepted.
   *
   * It is an infinite response: the network-first handler below would await
   * `fetch()` and then hold a response that never completes, and any attempt
   * to cache it would buffer forever. Falling through to the browser lets
   * EventSource own the connection, including its own reconnect.
   */
  if (url.pathname === '/api/events') return

  // Listening before importing: a range stream proxied from YouTube, never
  // worth caching, and the browser owns its connection best (a seek drops it).
  if (url.pathname === '/api/import/listen') return

  if (url.pathname.startsWith('/api/stream/')) {
    event.respondWith(handleAudio(request, url))
    return
  }

  if (url.pathname.startsWith('/api/art/')) {
    event.respondWith(cacheFirst(request, API_CACHE, { replaceOtherVersions: true }))
    return
  }

  if (url.pathname.startsWith('/api/')) {
    event.respondWith(networkFirst(request))
    return
  }

  event.respondWith(handleShell(request, url))
})

/**
 * Serve audio, honouring range requests from the cache.
 *
 * This is the function that makes offline playback actually work. The cache
 * holds a complete 200 response; a player asking for bytes 500-999 gets a
 * correctly-formed 206 slice built here, because the Cache API will not do it.
 */
async function handleAudio(request: Request, url: URL): Promise<Response> {
  const cache = await caches.open(AUDIO_CACHE)
  const cacheKey = url.pathname
  const cached = await cache.match(cacheKey)

  if (cached) {
    const range = request.headers.get('range')
    if (!range) return cached
    return sliceResponse(cached, range)
  }

  // Not cached — go to the network and do not store it. Songs enter the cache
  // only through an explicit sync, so casual listening cannot quietly fill up
  // the phone's storage.
  try {
    return await fetch(request)
  } catch {
    return new Response('This song is not available offline.', {
      status: 503,
      statusText: 'Offline',
      headers: { 'Content-Type': 'text/plain' },
    })
  }
}

/** Build a 206 Partial Content response from a complete cached one. */
async function sliceResponse(response: Response, rangeHeader: string): Promise<Response> {
  const buffer = await response.arrayBuffer()
  const size = buffer.byteLength

  const match = /^bytes=(\d*)-(\d*)$/.exec(rangeHeader.trim())
  if (!match) return new Response(buffer, { status: 200, headers: response.headers })

  const [, rawStart = '', rawEnd = ''] = match

  let start: number
  let end: number

  if (rawStart === '') {
    // Suffix range: the last N bytes.
    const suffix = Number(rawEnd)
    if (!Number.isFinite(suffix) || suffix <= 0) return rangeNotSatisfiable(size)
    start = Math.max(0, size - suffix)
    end = size - 1
  } else {
    start = Number(rawStart)
    end = rawEnd === '' ? size - 1 : Math.min(Number(rawEnd), size - 1)
  }

  if (!Number.isFinite(start) || !Number.isFinite(end) || start > end || start >= size) {
    return rangeNotSatisfiable(size)
  }

  const headers = new Headers()
  headers.set('Content-Type', response.headers.get('content-type') ?? 'audio/mp4')
  headers.set('Content-Length', String(end - start + 1))
  headers.set('Content-Range', `bytes ${start}-${end}/${size}`)
  headers.set('Accept-Ranges', 'bytes')
  headers.set('Cache-Control', 'private, max-age=31536000, immutable')

  return new Response(buffer.slice(start, end + 1), {
    status: 206,
    statusText: 'Partial Content',
    headers,
  })
}

function rangeNotSatisfiable(size: number): Response {
  return new Response(null, {
    status: 416,
    statusText: 'Range Not Satisfiable',
    headers: { 'Content-Range': `bytes */${size}` },
  })
}

/**
 * API requests: network first, falling back to the last good response.
 *
 * Only safe, idempotent reads are cached, and only the library snapshot is
 * worth serving stale — the import queue or live stats would be actively
 * misleading if they were hours old.
 */
async function networkFirst(request: Request): Promise<Response> {
  const cacheable = new URL(request.url).pathname === '/api/library'

  try {
    const response = await fetch(request)
    if (cacheable && response.ok) {
      const cache = await caches.open(API_CACHE)
      await cache.put(request, response.clone())
    }
    return response
  } catch {
    if (cacheable) {
      const cached = await caches.match(request)
      if (cached) return cached
    }
    return new Response(JSON.stringify({ error: 'offline', code: 'offline' }), {
      status: 503,
      headers: { 'Content-Type': 'application/json' },
    })
  }
}

/**
 * Cache-first, keyed on the full URL including `?v=`.
 *
 * With `replaceOtherVersions`, storing a response first drops every other
 * version of the same path, so a cover that changes does not leave the old
 * one behind forever.
 */
async function cacheFirst(
  request: Request,
  cacheName: string,
  options: { replaceOtherVersions?: boolean } = {},
): Promise<Response> {
  const cached = await caches.match(request)
  if (cached) return cached
  try {
    const response = await fetch(request)
    if (response.ok) {
      const cache = await caches.open(cacheName)
      if (options.replaceOtherVersions) {
        await cache.delete(new URL(request.url).pathname, { ignoreSearch: true })
      }
      await cache.put(request, response.clone())
    }
    return response
  } catch {
    return new Response(null, { status: 503 })
  }
}

/**
 * The app shell.
 *
 * Navigations always resolve to `index.html` so client-side routes work
 * offline — opening the app on `/stats` with no network must not 404.
 */
async function handleShell(request: Request, url: URL): Promise<Response> {
  const cache = await caches.open(SHELL_CACHE)

  if (request.mode === 'navigate') {
    try {
      const response = await fetch(request)
      if (response.ok) await cache.put('/index.html', response.clone())
      return response
    } catch {
      const cached = (await cache.match('/index.html')) ?? (await cache.match('/'))
      return cached ?? new Response('Offline', { status: 503 })
    }
  }

  const cached = await cache.match(request)
  if (cached) {
    // Refresh in the background so the next load has the new build, without
    // making this one wait for the network.
    void (async () => {
      try {
        const fresh = await fetch(request)
        if (fresh.ok) await cache.put(request, fresh)
      } catch {
        // Offline: the cached copy stays.
      }
    })()
    return cached
  }

  try {
    const response = await fetch(request)
    // Only cache our own build output, not arbitrary paths.
    if (response.ok && (url.pathname.startsWith('/assets/') || url.pathname.startsWith('/icons/'))) {
      await cache.put(request, response.clone())
    }
    return response
  } catch {
    return new Response(null, { status: 503 })
  }
}

export {}
