/// <reference lib="webworker" />

/**
 * self.mp3 service worker.
 *
 * Three jobs, each with a deliberately different strategy:
 *
 *  1. **App shell** — cache-first with a background update. The app opens
 *     instantly and offline; a new build is picked up on the next visit.
 *  2. **Audio** — cache-first, and critically it answers range requests out of
 *     the cache. Without that, iOS Safari will not play a cached file at all,
 *     because it always asks for `Range: bytes=0-1` first.
 *  3. **API** — network-first with a cached fallback for the library, so a
 *     sleeping Mac degrades to "yesterday's library" rather than an error.
 *
 * Built for the web (GitHub Pages, docs/SYNC.md) there is no Mac: a song or a
 * cover this device does not have yet is fetched from the bucket through the
 * doorman instead, with the session the app keeps in IndexedDB. The player's
 * range goes to the bucket as it is, so a song streams rather than having to
 * arrive whole; only what the page asks to keep is kept.
 *
 * The app may live under a path (`/selfmp3/` on Pages), so every path here is
 * taken relative to the scope this worker was registered with.
 *
 * Written by hand rather than generated by Workbox: the range-request handling
 * is the whole point of this file and is not something a generic recipe does.
 */

declare const self: ServiceWorkerGlobalScope

/**
 * A stamp the build replaces, so each build's shell is its own cache.
 *
 * The shell holds hashed asset files, which a new build renames rather than
 * overwrites. With one fixed cache name nothing ever went out of it: every
 * build's superseded JavaScript and CSS stayed on the device for good. Naming
 * the cache after the build means `activate` sweeps the last one away as part
 * of what it already does. Left as `dev` when nothing substitutes it, which is
 * what `vite dev` wants anyway — one cache it keeps reusing.
 */
declare const __SHELL_BUILD__: string
const SHELL_BUILD = typeof __SHELL_BUILD__ === 'string' ? __SHELL_BUILD__ : 'dev'

const SHELL_CACHE = `selfmp3-shell-${SHELL_BUILD}`
/*
 * These two are deliberately *not* named after the build: what they hold is
 * the person's, not this build's. Yesterday's library is what a sleeping Mac
 * degrades to, and re-downloading every song on a deploy is unthinkable.
 */
const API_CACHE = 'selfmp3-api-v1'
const AUDIO_CACHE = 'selfmp3-audio-v1'

/** Caches this worker owns. Anything else from an old build gets deleted. */
const OWNED_CACHES = new Set([SHELL_CACHE, API_CACHE, AUDIO_CACHE])

/** `/` served by the Mac, `/selfmp3/` on GitHub Pages: this worker's scope. */
const BASE = new URL(self.registration.scope).pathname

/**
 * How a download says it wants the file itself, not the copy already kept.
 *
 * Spelled out here rather than imported: this worker has no imports on
 * purpose, so that what esbuild bundles is exactly this file. The other half
 * is `REFRESH_HEADER` in src/ports/offline.web.ts, and the two have to agree.
 */
const REFRESH_HEADER = 'x-selfmp3-refresh'

/** Registered as `sw.js?cloud=1` when signed in to the cloud (src/ports/serviceWorker.web.ts): only then is there a bucket to ask. */
const CLOUD = new URL(self.location.href).searchParams.get('cloud') === '1'
const INDEX = `${BASE}index.html`

const SHELL_URLS = [BASE, INDEX, `${BASE}manifest.webmanifest`, `${BASE}icons/icon.svg`]

self.addEventListener('install', event => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(SHELL_CACHE)
      // Individually, so one 404 does not fail the whole install.
      await Promise.allSettled(SHELL_URLS.map(url => cache.add(url)))
      // Take over immediately; waiting for every tab to close is not the
      // behaviour anyone wants from their own music app.
      await self.skipWaiting()
    })(),
  )
})

self.addEventListener('activate', event => {
  event.waitUntil(
    (async () => {
      const names = await caches.keys()
      await Promise.all(
        names
          .filter(name => name.startsWith('selfmp3-') && !OWNED_CACHES.has(name))
          .map(name => caches.delete(name)),
      )
      // The library an older worker kept (networkFirst): stale by now, and
      // nothing serves it any more.
      await (await caches.open(API_CACHE)).delete(`${BASE}api/library`)
      await self.clients.claim()
    })(),
  )
})

self.addEventListener('message', event => {
  const data: unknown = event.data
  if (typeof data === 'object' && data !== null && 'type' in data) {
    if ((data as { type: string }).type === 'SKIP_WAITING') void self.skipWaiting()
  }
})

self.addEventListener('fetch', event => {
  const request = event.request
  if (request.method !== 'GET' && request.method !== 'HEAD') return

  const url = new URL(request.url)
  // Never touch cross-origin requests (album art from a thumbnail host, etc).
  if (url.origin !== self.location.origin) return

  /*
   * The event stream is never intercepted.
   *
   * It is an infinite response: the network-first handler below would await
   * `fetch()` and then hold a response that never completes, and any attempt
   * to cache it would buffer forever. Falling through to the browser lets
   * EventSource own the connection, including its own reconnect.
   */
  if (url.pathname === `${BASE}api/events`) return

  // Listening before importing: a range stream proxied from YouTube, never
  // worth caching, and the browser owns its connection best (a seek drops it).
  if (url.pathname === `${BASE}api/import/listen`) return

  if (url.pathname.startsWith(`${BASE}api/stream/`)) {
    event.respondWith(handleAudio(request, url))
    return
  }

  if (url.pathname.startsWith(`${BASE}api/art/`)) {
    event.respondWith(cacheFirst(request, API_CACHE, { replaceOtherVersions: true }))
    return
  }

  if (url.pathname.startsWith(`${BASE}api/`)) {
    event.respondWith(networkFirst(request))
    return
  }

  event.respondWith(handleShell(request, url))
})

/**
 * Serve audio: from this device when it is here, from the bucket when it is not.
 *
 * A downloaded song is a complete 200 in the cache, and a player asking for
 * bytes 500-999 gets a correctly-formed 206 slice built here, because the
 * Cache API will not do it. A song that was never downloaded is streamed from
 * the bucket a range at a time and kept nowhere — a library of a thousand
 * songs is not something a browser tab should quietly copy.
 */
async function handleAudio(request: Request, url: URL): Promise<Response> {
  const cache = await caches.open(AUDIO_CACHE)
  const cacheKey = url.pathname

  /*
   * A download saying it wants fresh bytes gets them.
   *
   * `cache: 'reload'` only skips the browser's HTTP cache — this worker sits
   * in front of that and would hand back the copy the page is trying to
   * replace, so a song whose file changed on the Mac could never be refreshed
   * and every pass re-stored what it already had. The page asks with a header
   * rather than a query, since what is stored is keyed by path alone.
   */
  const wantsFresh = request.headers.get(REFRESH_HEADER) !== null
  // The page keeps a download under its whole stream address, `?v=` and all,
  // and the player may ask with another query: the path is what names a song.
  const cached = wantsFresh ? undefined : await cache.match(cacheKey, { ignoreSearch: true })

  if (cached) {
    const range = request.headers.get('range')
    if (!range) return cached
    return sliceResponse(cached, range)
  }

  // A download asks for the whole file and the page keeps what comes back;
  // the player asks for a range and nothing is kept. Either way the bucket
  // answers the request that was made, through the doorman.
  const fromBucket = await bucketFileFor(url, 'audio')
  if (fromBucket) return fetchFromBucket(fromBucket, request.headers.get('range'))

  // Served by the Mac, and not on this device: go to the network and store
  // nothing. What this cache holds is the page's decision, never a side
  // effect of playing something (src/ports/offline.web.ts).
  try {
    return await fetch(request)
  } catch {
    return new Response('This song is not available offline.', {
      status: 503,
      statusText: 'Offline',
      headers: { 'Content-Type': 'text/plain' },
    })
  }
}

/**
 * Build a 206 Partial Content response from a complete cached one.
 *
 * Through a blob, not an array buffer: a player asks for a song a range at a
 * time, and reading the whole file into this worker's memory for each range
 * was a song's worth of copying per seek. A cached response's blob is backed
 * by the cache on disk, and slicing it copies nothing until the bytes are read.
 */
async function sliceResponse(response: Response, rangeHeader: string): Promise<Response> {
  const match = /^bytes=(\d*)-(\d*)$/.exec(rangeHeader.trim())
  if (!match) return response

  const blob = await response.blob()
  const size = blob.size

  const [, rawStart = '', rawEnd = ''] = match

  let start: number
  let end: number

  if (rawStart === '') {
    // Suffix range: the last N bytes.
    const suffix = Number(rawEnd)
    if (!Number.isFinite(suffix) || suffix <= 0) return rangeNotSatisfiable(size)
    start = Math.max(0, size - suffix)
    end = size - 1
  } else {
    start = Number(rawStart)
    end = rawEnd === '' ? size - 1 : Math.min(Number(rawEnd), size - 1)
  }

  if (!Number.isFinite(start) || !Number.isFinite(end) || start > end || start >= size) {
    return rangeNotSatisfiable(size)
  }

  const headers = new Headers()
  headers.set('Content-Type', response.headers.get('content-type') ?? 'audio/mp4')
  headers.set('Content-Length', String(end - start + 1))
  headers.set('Content-Range', `bytes ${start}-${end}/${size}`)
  headers.set('Accept-Ranges', 'bytes')
  headers.set('Cache-Control', 'private, max-age=31536000, immutable')

  return new Response(blob.slice(start, end + 1), {
    status: 206,
    statusText: 'Partial Content',
    headers,
  })
}

function rangeNotSatisfiable(size: number): Response {
  return new Response(null, {
    status: 416,
    statusText: 'Range Not Satisfiable',
    headers: { 'Content-Range': `bytes */${size}` },
  })
}

/**
 * API requests: the network, and an honest "offline" when it is not there.
 *
 * Nothing is kept. The library used to be — a second copy of it put into the
 * Cache API on every fetch, beside the one the page already saves in
 * IndexedDB (src/offline/libraryCache.web.ts) — and served stale as a 200 when
 * the Mac was away, which told the page it was answered when it was not. The
 * page's own copy does that job, and shows the copy for what it is.
 */
async function networkFirst(request: Request): Promise<Response> {
  try {
    return await fetch(request)
  } catch {
    return new Response(JSON.stringify({ error: 'offline', code: 'offline' }), {
      status: 503,
      headers: { 'Content-Type': 'application/json' },
    })
  }
}

/**
 * Cache-first, keyed on the full URL including `?v=`.
 *
 * With `replaceOtherVersions`, storing a response first drops every other
 * version of the same path, so a cover that changes does not leave the old
 * one behind forever.
 */
async function cacheFirst(
  request: Request,
  cacheName: string,
  options: { replaceOtherVersions?: boolean } = {},
): Promise<Response> {
  const cached = await caches.match(request)
  if (cached) return cached
  try {
    const fromBucket = await bucketFileFor(new URL(request.url), 'cover')
    const response = fromBucket ? await fetchFromBucket(fromBucket) : await fetch(request)
    if (response.ok) {
      const cache = await caches.open(cacheName)
      if (options.replaceOtherVersions) {
        await cache.delete(new URL(request.url).pathname, { ignoreSearch: true })
      }
      await cache.put(request, response.clone())
    }
    return response
  } catch {
    return new Response(null, { status: 503 })
  }
}

/**
 * The app shell.
 *
 * Navigations always resolve to `index.html` so client-side routes work
 * offline — opening the app on `/stats` with no network must not 404.
 */
async function handleShell(request: Request, url: URL): Promise<Response> {
  const cache = await caches.open(SHELL_CACHE)

  if (request.mode === 'navigate') {
    try {
      const response = await fetch(request)
      if (response.ok) await cache.put(INDEX, response.clone())
      return response
    } catch {
      const cached = (await cache.match(INDEX)) ?? (await cache.match(BASE))
      return cached ?? new Response('Offline', { status: 503 })
    }
  }

  const cached = await cache.match(request)
  if (cached) {
    // Refresh in the background so the next load has the new build, without
    // making this one wait for the network.
    void (async () => {
      try {
        const fresh = await fetch(request)
        if (fresh.ok) await cache.put(request, fresh)
      } catch {
        // Offline: the cached copy stays.
      }
    })()
    return cached
  }

  try {
    const response = await fetch(request)
    // Only cache our own build output, not arbitrary paths.
    const ownOutput =
      url.pathname.startsWith(`${BASE}_expo/`) ||
      url.pathname.startsWith(`${BASE}assets/`) ||
      url.pathname.startsWith(`${BASE}icons/`)
    if (response.ok && ownOutput) {
      await cache.put(request, response.clone())
    }
    return response
  } catch {
    return new Response(null, { status: 503 })
  }
}

// --- The bucket, for the web build --------------------------------------------

/**
 * Where the app keeps the doorman session and each song's files: IndexedDB,
 * database `selfmp3`, store `kv` — see src/ports/idbStore.web.ts, and packages/cloud's
 * session.ts (`cloud-session`) and library.ts (`cloud-files`).
 */
const DB_NAME = 'selfmp3'
const DB_STORE = 'kv'
/** src/ports/idbStore.web.ts's DB_VERSION. Opened with the same version and upgrade, whoever gets there first. */
const DB_VERSION = 1

interface BucketFile {
  readonly url: string
  readonly token: string
}

/**
 * The bucket file behind a stream or cover URL, when the app is signed in to
 * the doorman — which only the web build is. Null otherwise: served by the
 * Mac, nothing here changes.
 */
async function bucketFileFor(url: URL, kind: 'audio' | 'cover'): Promise<BucketFile | null> {
  if (!CLOUD) return null
  const match = /\/api\/(?:stream|art)\/(\d+)$/.exec(url.pathname)
  const songId = match?.[1]
  if (!songId) return null
  try {
    let read = await bucketRead(false)
    // A song added a moment ago, or a session just made: not a miss yet.
    if (!read.fresh && (!read.session || read.files?.[songId] === undefined)) {
      read = await bucketRead(true)
    }
    const key = read.files?.[songId]?.[kind]
    if (!read.session || typeof key !== 'string') return null
    return { url: `${read.session.doormanUrl}/v1/files/${key}`, token: read.session.token }
  } catch {
    return null
  }
}

/**
 * How long the session and the song files read from IndexedDB are trusted.
 *
 * Every range the player asks for, and every cover, comes through
 * bucketFileFor, and each used to open the database twice and copy the whole
 * library's file map out of it — per request, all through a song. Kept this
 * long, a file changed on another device or a token renewed is picked up
 * within seconds; an id not in the map at all is read again at once.
 */
const BUCKET_READ_MS = 5_000

interface BucketRead {
  readonly session: { doormanUrl: string; token: string } | null
  readonly files: Record<string, { audio?: unknown; cover?: unknown } | undefined> | null
  readonly at: number
}

let lastBucketRead: BucketRead | null = null

async function bucketRead(force: boolean): Promise<BucketRead & { fresh: boolean }> {
  const kept = lastBucketRead
  if (!force && kept && Date.now() - kept.at < BUCKET_READ_MS) return { ...kept, fresh: false }
  const [session, files] = await readStored(['cloud-session', 'cloud-files'])
  const stored = session as { doormanUrl?: unknown; token?: unknown } | null
  lastBucketRead = {
    session:
      typeof stored?.doormanUrl === 'string' && typeof stored.token === 'string'
        ? { doormanUrl: stored.doormanUrl, token: stored.token }
        : null,
    files: typeof files === 'object' && files !== null ? (files as BucketRead['files']) : null,
    at: Date.now(),
  }
  return { ...lastBucketRead, fresh: true }
}

/**
 * A file from the bucket, as a plain same-origin response.
 *
 * A range asked for here is asked of the bucket too, and its answer — a 206,
 * a `content-range` — comes back as it is, so a song plays and seeks while it
 * arrives instead of after it. The bytes are passed straight on: the doorman
 * never holds a body whole, and neither does this.
 */
async function fetchFromBucket(file: BucketFile, range?: string | null): Promise<Response> {
  try {
    const ask = new Headers({ Authorization: `Bearer ${file.token}` })
    if (range) ask.set('range', range)
    const response = await fetch(file.url, { headers: ask })
    const headers = new Headers()
    for (const name of [
      'content-type',
      'content-length',
      'content-range',
      'accept-ranges',
      'etag',
    ]) {
      const value = response.headers.get(name)
      if (value) headers.set(name, value)
    }
    // A whole file is the one the hash names, forever. A slice of one is the
    // player's business for as long as it is playing, and no cache's.
    headers.set(
      'Cache-Control',
      response.status === 206 ? 'no-store' : 'private, max-age=31536000, immutable',
    )
    return new Response(response.body, { status: response.status, headers })
  } catch {
    return new Response('This song is not on this device, and the cloud cannot be reached.', {
      status: 503,
      statusText: 'Offline',
      headers: { 'Content-Type': 'text/plain' },
    })
  }
}

/** Several keys, in one opening of the database and one transaction. */
function readStored(keys: readonly string[]): Promise<unknown[]> {
  return new Promise((resolve, reject) => {
    const open = indexedDB.open(DB_NAME, DB_VERSION)
    open.onupgradeneeded = () => {
      if (!open.result.objectStoreNames.contains(DB_STORE)) open.result.createObjectStore(DB_STORE)
    }
    open.onerror = () => reject(open.error ?? new Error('could not open IndexedDB'))
    open.onsuccess = () => {
      const db = open.result
      if (!db.objectStoreNames.contains(DB_STORE)) {
        db.close()
        resolve(keys.map(() => null))
        return
      }
      const transaction = db.transaction(DB_STORE, 'readonly')
      const store = transaction.objectStore(DB_STORE)
      const requests = keys.map(key => store.get(key))
      transaction.oncomplete = () => {
        db.close()
        resolve(requests.map(request => (request.result as unknown) ?? null))
      }
      transaction.onerror = () => {
        db.close()
        reject(transaction.error ?? new Error('IndexedDB read failed'))
      }
    }
  })
}

export {}
