/**
 * CarPlay config plugin.
 *
 * react-native-carplay needs three things that only exist in native project
 * files, which is why this is a config plugin rather than app.config.js keys:
 *
 *  1. the `com.apple.developer.carplay-audio` entitlement,
 *  2. a `UIApplicationSceneManifest` declaring a CarPlay scene, and
 *  3. a `CPTemplateApplicationSceneDelegate` subclass that hands the CarPlay
 *     interface controller to `RNCarPlay`.
 *
 * (3) is written as Objective-C rather than Swift on purpose: the RNCarPlay
 * header is a plain Objective-C header inside a non-modular pod, so ObjC can
 * `#import` it directly while Swift would need a bridging-header edit that is
 * far more fragile to automate.
 *
 * The scene manifest only declares the CarPlay role. The phone UI keeps using
 * the window created in AppDelegate, which is what react-native-carplay
 * expects and what lets the app run normally with no car attached.
 *
 * The entitlement is inert until Apple grants it to the bundle id — see
 * docs/MOBILE.md. A build signed without it simply never shows up in the car;
 * nothing else about the app changes.
 */

const fs = require('node:fs')
const path = require('node:path')

const { withEntitlementsPlist, withInfoPlist, withXcodeProject, IOSConfig } = require('expo/config-plugins')

const DELEGATE_CLASS = 'SelfMp3CarSceneDelegate'
const SCENE_CONFIGURATION_NAME = 'self.mp3-CarPlay'

const HEADER_SOURCE = `// Generated by apps/mobile/plugins/withCarPlay.js — do not edit by hand.
#import <CarPlay/CarPlay.h>
#import <UIKit/UIKit.h>

@interface ${DELEGATE_CLASS} : UIResponder <CPTemplateApplicationSceneDelegate>
@end
`

const IMPLEMENTATION_SOURCE = `// Generated by apps/mobile/plugins/withCarPlay.js — do not edit by hand.
//
// CarPlay hands us an interface controller when the head unit connects. All we
// do is forward it to RNCarPlay, which raises the "didConnect" event that
// src/car/carplay.ts listens for and builds the templates from JavaScript.
#import "${DELEGATE_CLASS}.h"
#import <react-native-carplay/RNCarPlay.h>

@implementation ${DELEGATE_CLASS}

- (void)templateApplicationScene:(CPTemplateApplicationScene *)templateApplicationScene
    didConnectInterfaceController:(CPInterfaceController *)interfaceController
                        toWindow:(CPWindow *)window {
  [RNCarPlay connectWithInterfaceController:interfaceController window:window];
}

- (void)templateApplicationScene:(CPTemplateApplicationScene *)templateApplicationScene
 didDisconnectInterfaceController:(CPInterfaceController *)interfaceController
                       fromWindow:(CPWindow *)window {
  [RNCarPlay disconnect];
}

@end
`

/** The entitlement itself. Harmless when Apple has not granted it yet. */
const withCarPlayEntitlement = config =>
  withEntitlementsPlist(config, mod => {
    mod.modResults['com.apple.developer.carplay-audio'] = true
    return mod
  })

/**
 * Declare the CarPlay scene. Only the CarPlay role is listed, so the phone app
 * keeps its existing (non-scene) lifecycle.
 */
const withCarPlaySceneManifest = config =>
  withInfoPlist(config, mod => {
    const existing = mod.modResults['UIApplicationSceneManifest'] ?? {}
    const configurations = existing.UISceneConfigurations ?? {}

    mod.modResults['UIApplicationSceneManifest'] = {
      ...existing,
      UIApplicationSupportsMultipleScenes: true,
      UISceneConfigurations: {
        ...configurations,
        CPTemplateApplicationSceneSessionRoleApplication: [
          {
            UISceneClassName: 'CPTemplateApplicationScene',
            UISceneConfigurationName: SCENE_CONFIGURATION_NAME,
            UISceneDelegateClassName: DELEGATE_CLASS,
          },
        ],
      },
    }
    return mod
  })

/**
 * Write the scene delegate into the iOS project and add the .m to the app
 * target's compile sources. Both steps are idempotent, because prebuild may
 * run many times over the same folder.
 */
const withCarPlaySceneDelegate = config =>
  withXcodeProject(config, mod => {
    // getProjectName resolves ios/<Name> from the AppDelegate, so it takes the
    // app root rather than the platform folder.
    const projectName = IOSConfig.XcodeUtils.getProjectName(mod.modRequest.projectRoot)
    const groupDirectory = path.join(mod.modRequest.platformProjectRoot, projectName)

    fs.mkdirSync(groupDirectory, { recursive: true })
    fs.writeFileSync(path.join(groupDirectory, `${DELEGATE_CLASS}.h`), HEADER_SOURCE, 'utf8')
    fs.writeFileSync(path.join(groupDirectory, `${DELEGATE_CLASS}.m`), IMPLEMENTATION_SOURCE, 'utf8')

    // A second prebuild over the same folder is a no-op: the helper skips a
    // file whose basename is already a child of the group.
    IOSConfig.XcodeUtils.addBuildSourceFileToGroup({
      filepath: `${projectName}/${DELEGATE_CLASS}.m`,
      groupName: projectName,
      project: mod.modResults,
    })

    return mod
  })

module.exports = function withCarPlay(config) {
  return withCarPlaySceneDelegate(withCarPlaySceneManifest(withCarPlayEntitlement(config)))
}
